console.log("La granjera 2:");
console.log("avanzar");
console.log("llenar");
console.log("avanzar");
console.log("avanzar");
console.log("avanzar");
console.log("llenar");
console.log("avanzar");
console.log("eliminar");
console.log("avanzar");
console.log("eliminar");
